# Dockerfile.nginx

FROM nginx:alpine

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the built frontend files from the dist directory
COPY frontend/src/dist /usr/share/nginx/html

